### ISSUE TITLE
Nginx proxy

### ISSUE THREAD

**Issue by vk496** [c9/core#132]
Im trying to use cloud9 over nginx proxy on port 80 but get 404 error

My nginx config:
```
location /cloud9/ {
        rewrite /cloud9/(.*) /$1  break;
        proxy_pass http://localhost:7777;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $host;
        proxy_redirect     off;
} 
```

Anyone can help?

**Comment by nightwing** [comment]
Rewriting this way doesn't work because ide needs to access /static and /vfs urls at
https://github.com/c9/core/blob/master/settings/standalone.js#L60
https://github.com/c9/core/blob/master/plugins/c9.vfs.client/endpoint.js#L66
and possibly some others.

Merging this issue into https://github.com/c9/core/issues/11.
