### ISSUE TITLE
Issues with terminal

### ISSUE THREAD

**Issue by datianshi** [c9/core#203]
The IDE is up but the terminal is not working
See the below error that it was looking into a app folder. Any clue on this error?

ERR { [Error: Cannot find module 'app/.c9/node_modules/pty.js'] code: 'MODULE_NOT_FOUND' } 'app/.c9/node_modules/pty.js'
ERR { [Error: Cannot find module 'pty.js'] code: 'MODULE_NOT_FOUND' } 'pty.js'
ERR { [Error: Cannot find module 'pty.nw.js'] code: 'MODULE_NOT_FOUND' } 'pty.nw.js'
2015-11-04T08:05:41.88-0600 [APP/0]      ERR unable to initialize pty.js:

**Comment by nightwing** [comment]
It is supposed to look into home folder, 
could you add console.log calls at https://github.com/c9/core/blob/master/node_modules/vfs-local/localfs.js#L74 to see what are values of `fsOptions.nodePath` and `process.env.HOME`

**Comment by datianshi** [comment]
@nightwing Thanks for the tip
I was deploying to cloudfoundry with a docker container. cloudfoundry has a default env.Home which point to the app directory causing the issue. Do you know how to set fsOptions.nodePath thought cloud9 start up command?

**Comment by nightwing** [comment]
It can be passed from https://github.com/c9/core/blob/master/plugins/c9.vfs.server/vfs.connect.standalone.js#L47, but there are several other places that require `process.env.HOME` to be absolute path to an existing and writable directory.

An easy workaround would be to run `export HOME=/some/writable/path` before running c9 server.
Note that pty.js is installed to $HOME/.c9 by [install-sdk.sh](https://github.com/c9/core/blob/master/scripts/install-sdk.sh) script, so that needs to run again after changing HOME variable.

**Comment by datianshi** [comment]
Thanks for help.
