### ISSUE TITLE
can C9  develop android app?

### ISSUE THREAD

**Issue by soitun** [c9/core#326]
can C9  develop android app?

**Comment by georgir** [comment]
Since you get a terminal with root access, you can do most anything on c9.
Android SDK takes up a lot of space though, so it's not going to work with a free c9.io account. With a paid account so you can have a larger workspace, a ssh workspace or with a locally installed c9 server it should work fine.

You can not (easily) run GUI apps on c9 though, so installing and later updating the Android SDK may be tricky. You'll have to learn the command line options of the android update manager. Similarly, you can not easily run the android emulator to test your app right on c9, but you can get the built apk from c9 to your local box and then test it there, in emulator or even on a real device.

There are ways around even that "no GUI apps" restriction, with forwarding X traffic through ssh or with setting up a xvnc server or probably many others, but I guess this is getting a bit too deep for the simple question you asked.
