### ISSUE TITLE
Tab key is not working in html language syntax

### ISSUE THREAD

**Issue by portokallidis** [c9/core#373]
I am facing a weird bug,
The tab key is not working when i am editing html files.
The shift+tab for backindent is working fine though!

I have tried all popular browsers and it's not a browser thing.

Also if i manually choose indent from the menu its working fine.
It's like the key-binding(tab) for html syntax is somehow blocked

**Comment by nightwing** [comment]
are there any errors in browser console? Maybe emmet is missing?

**Comment by portokallidis** [comment]
Thank you for the interest, but i cant see any errors regarding the emmet.
I finally found the bug and its in the --packed param for some reason.
When i run c9 without the --packed param i dont have this problem.

**Comment by iox** [comment]
I have reproduced this issue in different computers.

It turns out that the packed version of the JS is unable to load emmet. When you press `tab`, the emmet extension tries asking Emmet to check if the user wants to expand an abbreviation, or if he actually wants to indent. But emmet is not available, and then, it breaks silently.

I have found a workaround that works fine for me. In `plugins/c9.ide.ace.emmet/emmet.js`, you can change a couple of lines to preload emmet:

```diff
+       window.emmet = require("lib/emmet/emmet");
        var emmetExt = require("ace/ext/emmet");
-       emmetExt.setCore("lib/emmet/emmet");
```

After making this change, remember to delete your cached JS in `build/standalone/config/default.js` and reloading the page. Now your tabs should work without having to abandon the --packed option.
