### ISSUE TITLE
Workspace not working

### ISSUE THREAD

**Issue by danger89** [c9/core#376]
Is it just me or does the -w flag doesn't work anymore??

I use:
`/usr/bin/nodemon /var/www/c9.melroy.org/html/server.js -p 8181 -w /media/data/cloud9_workplace`

The workplace is now still `/var/www/c9.melroy.org/html` instead of `/media/data/cloud9_workplace`.

It's really a shame, because I'm not locked into this `html` folder with the editor :(. It looks like the `-w` is not exported from nodemon to the sub-node process, but other variables are... Uh, why?

![strange](https://cloud.githubusercontent.com/assets/628926/19807595/1a211734-9d21-11e6-882f-67554f2d7105.png)

Thx!
- Melroy

**Comment by nightwing** [comment]
i can't reproduce this issue, are there any errors in the server output?

**Comment by danger89** [comment]
Did you use nodemon instead of node to start the Cloud9 server? Like:
`/usr/bin/nodemon /var/www/yourdomain/html/server.js -p 8181 -w /your_location`

**Comment by danger89** [comment]
Output with node vs nodemon:
```
$:/var/www/c9.melroy.org/html$ /usr/bin/node /var/www/c9.melroy.org/html/server.js -p 8181 -w /media/data/cloud9_workplace        
Starting standalone    
Connect server listening at http://127.0.0.1:8181 
CDN: version standalone initialized /var/www/c9.melroy.org/html/build        
Started '/var/www/c9.melroy.org/html/configs/standalone' with config 'standalone'!    
Cloud9 is up and running        
cache /var/www/c9.melroy.org/html/build/standalone/skin/default/flat-light.css        
cache hit /var/www/c9.melroy.org/html/build/standalone/skin/default/flat-light.css    
387: Error: ENOENT, open '/media/data/cloud9_workplace/.c9/metadata/tab1'    
    at Error (native)  
```

See below the same line where -w is not used!
```
$/var/www/c9.melroy.org/html$ /usr/bin/nodemon /var/www/c9.melroy.org/html/server.js -p 8181 -w /media/data/cloud9_workplace     
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /media/data/cloud9_workplace/**/*
[nodemon] starting `node /var/www/c9.melroy.org/html/server.js -p 8181`
Starting standalone    
Connect server listening at http://127.0.0.1:8181 
CDN: version standalone initialized /var/www/c9.melroy.org/html/build        
Started '/var/www/c9.melroy.org/html/configs/standalone' with config 'standalone'!    
Cloud9 is up and running        
cache /var/www/c9.melroy.org/html/build/standalone/skin/default/flat-light.css        
cache hit /var/www/c9.melroy.org/html/build/standalone/skin/default/flat-light.css    
        588: Error: ENOENT, open '/var/www/c9.melroy.org/html/.c9/.nakignore'
    at Error (native)     
````

**Comment by nightwing** [comment]
that's an issue with nodemon, it uses -w for watch-dir flag (see `[nodemon] watching: /media/data/cloud9_workplace/**/*`) line, 
and starts cloud9 without -w, see <code>[nodemon] starting `node /var/www/c9.melroy.org/html/server.js -p 8181</code>

**Comment by danger89** [comment]
Ah I see, but this there actually a solution for it? Using quotes (") or something :s?...

**Comment by nightwing** [comment]
https://github.com/remy/nodemon/blob/2cd85b1f609e9749d19afcdbd71368e6ab063f9d/lib/cli/parse.js#L67 suggests using `--`
```
nodemon  --  server.js -p 8181 -w cloud9_workplace 
```
though stopping at the script path would be more user friendly, i think

**Comment by mirekphd** [comment]
Sadly, the workaround with using nodemon instead of node proposed by [nightwing](/nightwing) to avoid adding non-duplicate parameter name (-w is a duplicated parameter name and should not be used) did not work for me.

The -w parameter affects only the name displayed in the Workspace tab but does not change the actual folder mapping, which remains always the same, hard-coded to the home folder (~/). 

Combine this bug with the unusual requirement to install dependencies in the home folder (~/.c9) makes it impossible to access any external data from outside of the container (mapped with docker's -v parameter or a persistent volume claim in OpenShift). On an air-gapped server  you just can't download executables from the internet and install them to a hidden subfolder in a user folder at first run... to add insult to injury, the dialog requesting this risky operation cannot be even skipped at runtime...
