### ISSUE TITLE
Rail's Webpacker issue with localhost and 0.0.0.0 on C9 

### ISSUE THREAD

**Issue by ytbryan** [c9/core#405]
The issue is found here https://github.com/rails/webpacker/issues/176#issuecomment-290899738

**Comment by BigChief45** [comment]
I think it would be good idea to rename the title to include Webpack issues in Cloud 9.

**Comment by nightwing** [comment]
Seems like webpacker doesn't handle correctly the case when it is running behind a proxy, which i'd say is a bug. It assumes that host passed for listening is the same one which should be used for loading the scripts. Usually it is a good idea to use locathion.hostname on the client side, if the passed hostname is `0.0.0.0` (browserify does this)

As a workaround could you try adding a mapping from your preview hostname to `0.0.0.0` in `/etc/hosts`
```sh
echo "0.0.0.0 $C9_HOSTNAME" | sudo tee -a /etc/hosts
```
and then passing $C9_HOSTNAME instead of 0.0.0.0 to the webpacker?

**Comment by BigChief45** [comment]
@nightwing Thanks for chiming in.

I tried your suggestion. It does allow running the webpack dev server using $C9_HOSTNAME. However, when loading up the application, I find this in the browser console:

![c9_webpacker](https://cloud.githubusercontent.com/assets/6859247/24584867/8f0f25ec-17ae-11e7-960e-5844fb602f4a.JPG)

A detailed look into the response data of one of those requests shows:

```html
<html>
  <head>
    <meta charset='utf-8'> 
    <title>ECONNRESET: Request could not be proxied!</title>

<!-- ... -->
```

I am not sure if this is a C9 now, or if the `javascript_pack_tag` tags are pulling from the appropriate location...? 

CC @ytbryan

**Comment by nightwing** [comment]
@BigChief45 could you give me access to an example cloud9 workspace where i can debug this? I've tried to create one but didn't succeed as i am not familiar with ruby,

**Comment by BigChief45** [comment]
Give it another try and indeed modifying `/etc/hosts` as @nightwing suggested works. 

Thanks for all the help everyone. 

@ytbryan I think you can close this issue now.
