### ISSUE TITLE
Cannot find module 'c9/urls'

### ISSUE THREAD

**Issue by papac** [c9/core#472]
Ubuntu 16.04
Nodejs v8.9.4

After launch scripts/install-sdk.sh and start node server.
This error is comming

Cannot find module 'c9/urls'

 `npm run test` not work
the `test` scripts is not define in package.json

**Comment by nightwing** [comment]
This is caused by npm5 deleting all files in node_modules folder
run `git reset --hard` to restore the missing files.
or run `git fetch origin && git reset origin/HEAD--hard` to get the latest version, and then run `scripts/install-sdk.sh` again to get the fix from https://github.com/c9/core/commit/0f337beaf5ac04746ede7ff215b31cc1da16e544

**Comment by papac** [comment]
It's work.

**Comment by vkuehn** [comment]
still an issue and workaround is still ok
