### ISSUE TITLE
In-development plugins don't have __installed__.js

### ISSUE THREAD

**Issue by Pike** [c9/core#69]
I'm currently hacking on my own plugin, and after the landing of bundles, it seems that there's a requirement to have __installed__.js.

Just that I don't know how to get to one, without publishing and installing. Which doesn't work while you're developing, obviously.

I got something up when switching forceInstall to true for ~/.c9/plugins in loader.js, but that seems to just wallpaper over the underlying issue.

**Comment by nightwing** [comment]
Do you want to have an option to load development version (not packed into __installed__.js) of some plugins without `?debug=2` flag or just adding a command to create `__installed__.js` from c9 cli tool would be enough?

Note that there were two related issues, which were fixed today: 
Plugins not loading in debug mode, which was fixed by https://github.com/c9/core/commit/2da5c9a9dc0b9f6e7eb72ea459647ed390c80d32.
And loader printing spurious errors in the console was fixed by https://github.com/c9/core/commit/dbf4c64a9af8566de242bbd74d75746398467ba7.

**Comment by Hacksore** [comment]
I am unable to get my plugin running in debug mode or even when installed from the c9 cli.

**Comment by nightwing** [comment]
@Hacksore are you using sdk or c9.io? Unfortunately plugin loading on c9.io is broken now, it will be fixed on monday.

**Comment by Hacksore** [comment]
@nightwing I am in fact trying to use c9.io so I guess I'll wait it out.

**Comment by Pike** [comment]
I'm currently working locally with the sdk, and that's fixed, thanks.

Having to use debug=2 for development is a tad of a bummer, mostly because the green banner takes up quite a bit of screen space. It'd be good to have a way to do local setups that are good for dog fooding, or presentations.

I guess the c9.io issue is something around #68 ? Thus closing this.
