### ISSUE TITLE
c9 publish tar command is broken, and requires gnu-tar

### ISSUE THREAD

**Issue by Pike** [c9/core#75]
I tracked down a few issues with `c9 publish`.

Firstly, the '.' needs to be the last argument in the tar command. Also, --transform only works on gnu-tar, so not on macs. Probably should check if it can call gtar, and fall back to tar. The transform flag was also too quoted.

IMHO, c9 publish should be less opinionated on when to land stuff, and when to push. Or at least have an option to not do that. --dry-run does some of that, though it's somewhat surprising that it does that much.

Also, it should only do that on success.

**Comment by Pike** [comment]
diff --git a/plugins/c9.cli.publish/publish.js b/plugins/c9.cli.publish/publish.js
index 2ab55d9..4cd8f54 100644
--- a/plugins/c9.cli.publish/publish.js
+++ b/plugins/c9.cli.publish/publish.js
@@ -12,7 +12,7 @@ define(function(require, exports, module) {
         
         var TEST_MODE = !!process.env.C9_TEST_MODE;
         var SHELLSCRIPT = TEST_MODE ? "" : require("text!./publish.git.sh").toString("utf8");
-        var TAR = "tar";
+        var TAR = "gtar";
         var APIHOST = options.apiHost;
         var BASICAUTH = process.env.C9_TEST_AUTH;
         var SCM = {
@@ -733,7 +733,7 @@ define(function(require, exports, module) {
                 
                 function zip(ignore){
                     zipFilePath = join(os.tmpDir(), json.name + "@" + json.version) + ".tar.gz";
-                    var tarArgs = ["-zcvf", normalizePath(zipFilePath), "."]; 
+                    var tarArgs = ["-zcvf", normalizePath(zipFilePath)];
                     var c9ignore = normalizePath(process.env.HOME + "/.c9/.c9ignore");
                     fs.exists(c9ignore, function (exists) {
                         if (exists) {
@@ -745,7 +745,8 @@ define(function(require, exports, module) {
                                 tarArgs.push("--exclude=./" + normalizePath(p));
                             }
                         });
-                        tarArgs.push("--transform='flags=r;s|__packed__|__installed__|'");
+                        tarArgs.push("--transform=flags=r;s|__packed__|__installed__|");
+                        tarArgs.push(".");
                         // console.log(tarArgs)
                         proc.spawn(TAR, {
                             args: tarArgs,

**Comment by Pike** [comment]
Oh, one more nit, as I'm on it, it'd be nice if the build command would ignore .c9, .git, and .hg by default. I got those in a ~/.c9/.c9ignore now, but excluding them would be a better default.

**Comment by nightwing** [comment]
We can get rid of `--transform` param by copying all files to temporary directory before publishing

**Comment by invokr** [comment]
The '--transform' also breaks freebsd compatibilty for the same reason.

**Comment by nightwing** [comment]
This should be fixed with https://github.com/c9/core/commit/c9f66f2c88dc1a0063c81182bf784cbd22b74add and https://github.com/c9/core/commit/182577009f0ccf3c7ee9148671a1b28df26f81fc

now publish copies files to temporary dir to not use --transform and ignores .git .hg files by default

Also the default behaviour have changed to not create a tag and not increase a version, unless asked to do so by providing version or `--tag` flag

**Comment by Pike** [comment]
Thanks.

I left a comment about .c9build in one of the commits, and I also noticed that the tarball contains both __packed__.js and __installed__.js now

**Comment by Pike** [comment]
PS, the packed thing might have been a local problem.
But it seems that --dry-run doesn't leave the version number alone anymore?

**Comment by nightwing** [comment]
Thanks for noticing typo in .c9build
`__packed__.js` must have been the file created by old version. i didn't want to add special handling for that since
`c9 publish minor --dry-run` indeed updates the version, but `c9 publish --dry-run` and `c9 publish` do not. I thought it must be ok since version update is requested explicitly, but now i see it breaks running the command with dry-run before running for real.
